[package]
name = "users_service"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.5", features = ["default", "headers", "macros", "multipart", "ws"] }
tokio = { version = "1.20", features = ["full"] }
tower-http = { version = "0.3", features = ["trace"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
dotenv = "0.15"
sea-orm = { version = "0.9", features = ["runtime-tokio-rustls", "serde_json", "macros", "sqlx-postgres", "time"] }
serde = "1"
serde_json = "1"
validator = { version = "0.16", features = ["phone", "derive"]}
civilization = { path = "../../civilization" }
rand = "0.8"
time = { version = "0.3", features = ["serde-well-known"] }
chrono = "0.4"
uuid = { version = "1.1", features = ["v4", "fast-rng"] }
users-entities = { path = "./entities" }