//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

use sea_orm::entity::prelude::*;


#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique)]
    pub username: Option<String>,
    pub password: Option<String>,
    #[sea_orm(unique)]
    pub phone_number: String,
    pub firstname: String,
    pub lastname: String,
    pub sex: String,
    pub city: Option<String>,
    pub country: String,
    pub avatar: Option<String>,
    pub is_2fa_enabled: bool,
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
